// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3UpF-XBGsqFB6p_g0v2iEnD69hw5Trvg',
    appId: '1:914575261849:web:400aabcffa098d2ab83808',
    messagingSenderId: '914575261849',
    projectId: 'server-yemek-tarifi',
    authDomain: 'server-yemek-tarifi.firebaseapp.com',
    storageBucket: 'server-yemek-tarifi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmOKNYu5bugXyJ-fn2OB0Dle3BIrz6zg0',
    appId: '1:914575261849:android:1af618bd8d88302eb83808',
    messagingSenderId: '914575261849',
    projectId: 'server-yemek-tarifi',
    storageBucket: 'server-yemek-tarifi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvGbZjWzY8_vwFyX52Hk1WhRNHxDZNyd4',
    appId: '1:914575261849:ios:f435e3cc5f4b1389b83808',
    messagingSenderId: '914575261849',
    projectId: 'server-yemek-tarifi',
    storageBucket: 'server-yemek-tarifi.appspot.com',
    iosClientId: '914575261849-t98sm7rkokk1anitfa6b2666ibltf1du.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvGbZjWzY8_vwFyX52Hk1WhRNHxDZNyd4',
    appId: '1:914575261849:ios:f435e3cc5f4b1389b83808',
    messagingSenderId: '914575261849',
    projectId: 'server-yemek-tarifi',
    storageBucket: 'server-yemek-tarifi.appspot.com',
    iosClientId: '914575261849-t98sm7rkokk1anitfa6b2666ibltf1du.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
